[package]
name = "stdworkspace"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "adder", "advancefeatures",
    "chapters", 
    "collections", "concurrency", "drop", "functionallaguage", "minigrep", "oop", "patterns", "pointers", 
    "practices",
    "string",
]
[dependencies]
